window.BABYMAP_STATIONS = [
  {
    id: "station-shibuya",
    name: "渋谷駅",
    operator: "東京メトロ・東急電鉄・京王電鉄",
    lines: ["銀座線", "半蔵門線", "副都心線", "東横線", "田園都市線", "井の頭線"],
    lat: 35.658034,
    lng: 139.701636,
    aliases: ["渋谷"],
  },
  {
    id: "station-shinjuku",
    name: "新宿駅",
    operator: "都営地下鉄・京王電鉄・小田急電鉄",
    lines: ["新宿線", "大江戸線", "京王線", "小田原線"],
    lat: 35.689606,
    lng: 139.700571,
    aliases: ["新宿"],
  },
  {
    id: "station-ikebukuro",
    name: "池袋駅",
    operator: "東京メトロ・東武鉄道・西武鉄道",
    lines: ["丸ノ内線", "有楽町線", "副都心線", "東上線", "池袋線"],
    lat: 35.730256,
    lng: 139.711086,
    aliases: ["池袋"],
  },
  {
    id: "station-ginza",
    name: "銀座駅",
    operator: "東京メトロ",
    lines: ["銀座線", "丸ノ内線", "日比谷線"],
    lat: 35.671989,
    lng: 139.763965,
    aliases: ["銀座"],
  },
  {
    id: "station-nihombashi",
    name: "日本橋駅",
    operator: "東京メトロ・都営地下鉄",
    lines: ["銀座線", "東西線", "浅草線"],
    lat: 35.68205,
    lng: 139.77459,
    aliases: ["日本橋"],
  },
  {
    id: "station-mitsukoshimae",
    name: "三越前駅",
    operator: "東京メトロ",
    lines: ["銀座線", "半蔵門線"],
    lat: 35.68485,
    lng: 139.77329,
    aliases: ["三越前"],
  },
  {
    id: "station-otemachi",
    name: "大手町駅",
    operator: "東京メトロ・都営地下鉄",
    lines: ["丸ノ内線", "東西線", "千代田線", "半蔵門線", "三田線"],
    lat: 35.68446,
    lng: 139.76608,
    aliases: ["大手町"],
  },
  {
    id: "station-hibiya",
    name: "日比谷駅",
    operator: "東京メトロ・都営地下鉄",
    lines: ["日比谷線", "千代田線", "三田線"],
    lat: 35.6749,
    lng: 139.75974,
    aliases: ["日比谷"],
  },
  {
    id: "station-yurakucho",
    name: "有楽町駅",
    operator: "東京メトロ",
    lines: ["有楽町線"],
    lat: 35.67507,
    lng: 139.76333,
    aliases: ["有楽町"],
  },
  {
    id: "station-roppongi",
    name: "六本木駅",
    operator: "東京メトロ・都営地下鉄",
    lines: ["日比谷線", "大江戸線"],
    lat: 35.662836,
    lng: 139.731443,
    aliases: ["六本木"],
  },
  {
    id: "station-azabu-juban",
    name: "麻布十番駅",
    operator: "東京メトロ・都営地下鉄",
    lines: ["南北線", "大江戸線"],
    lat: 35.65468,
    lng: 139.73685,
    aliases: ["麻布十番"],
  },
  {
    id: "station-aoyama-itchome",
    name: "青山一丁目駅",
    operator: "東京メトロ・都営地下鉄",
    lines: ["銀座線", "半蔵門線", "大江戸線"],
    lat: 35.67284,
    lng: 139.72416,
    aliases: ["青山一丁目"],
  },
  {
    id: "station-omotesando",
    name: "表参道駅",
    operator: "東京メトロ",
    lines: ["銀座線", "千代田線", "半蔵門線"],
    lat: 35.66518,
    lng: 139.71246,
    aliases: ["表参道"],
  },
  {
    id: "station-tameike-sanno",
    name: "溜池山王駅",
    operator: "東京メトロ",
    lines: ["銀座線", "南北線"],
    lat: 35.67362,
    lng: 139.74161,
    aliases: ["溜池山王"],
  },
  {
    id: "station-toranomon-hills",
    name: "虎ノ門ヒルズ駅",
    operator: "東京メトロ",
    lines: ["日比谷線"],
    lat: 35.66639,
    lng: 139.74992,
    aliases: ["虎ノ門ヒルズ"],
  },
  {
    id: "station-kamiyacho",
    name: "神谷町駅",
    operator: "東京メトロ",
    lines: ["日比谷線"],
    lat: 35.66293,
    lng: 139.74506,
    aliases: ["神谷町"],
  },
  {
    id: "station-shirokane-takanawa",
    name: "白金高輪駅",
    operator: "東京メトロ・都営地下鉄",
    lines: ["南北線", "三田線"],
    lat: 35.64275,
    lng: 139.73405,
    aliases: ["白金高輪"],
  },
  {
    id: "station-shirokanedai",
    name: "白金台駅",
    operator: "東京メトロ・都営地下鉄",
    lines: ["南北線", "三田線"],
    lat: 35.63791,
    lng: 139.72613,
    aliases: ["白金台"],
  },
  {
    id: "station-mita",
    name: "三田駅",
    operator: "都営地下鉄",
    lines: ["浅草線", "三田線"],
    lat: 35.64811,
    lng: 139.74866,
    aliases: ["三田"],
  },
  {
    id: "station-daimon",
    name: "大門駅",
    operator: "都営地下鉄",
    lines: ["浅草線", "大江戸線"],
    lat: 35.65608,
    lng: 139.75468,
    aliases: ["大門"],
  },
  {
    id: "station-shimbashi",
    name: "新橋駅",
    operator: "東京メトロ・都営地下鉄・ゆりかもめ",
    lines: ["銀座線", "浅草線", "ゆりかもめ"],
    lat: 35.66632,
    lng: 139.75808,
    aliases: ["新橋"],
  },
  {
    id: "station-ueno",
    name: "上野駅",
    operator: "東京メトロ",
    lines: ["銀座線", "日比谷線"],
    lat: 35.713768,
    lng: 139.777254,
    aliases: ["上野"],
  },
  {
    id: "station-asakusa",
    name: "浅草駅",
    operator: "東京メトロ・都営地下鉄・東武鉄道",
    lines: ["銀座線", "浅草線", "伊勢崎線"],
    lat: 35.71056,
    lng: 139.79868,
    aliases: ["浅草"],
  },
  {
    id: "station-oshiage",
    name: "押上駅",
    operator: "東京メトロ・都営地下鉄・京成電鉄・東武鉄道",
    lines: ["半蔵門線", "浅草線", "押上線", "伊勢崎線"],
    lat: 35.71004,
    lng: 139.81293,
    aliases: ["押上", "スカイツリー前"],
  },
  {
    id: "station-kita-senju",
    name: "北千住駅",
    operator: "東京メトロ・東武鉄道・つくばエクスプレス",
    lines: ["日比谷線", "千代田線", "伊勢崎線", "つくばエクスプレス"],
    lat: 35.749046,
    lng: 139.804778,
    aliases: ["北千住"],
  },
  {
    id: "station-nishi-nippori",
    name: "西日暮里駅",
    operator: "東京メトロ・日暮里・舎人ライナー",
    lines: ["千代田線", "日暮里・舎人ライナー"],
    lat: 35.73215,
    lng: 139.76679,
    aliases: ["西日暮里"],
  },
  {
    id: "station-machiya",
    name: "町屋駅",
    operator: "東京メトロ・京成電鉄",
    lines: ["千代田線", "京成本線"],
    lat: 35.74221,
    lng: 139.78015,
    aliases: ["町屋"],
  },
  {
    id: "station-korakuen",
    name: "後楽園駅",
    operator: "東京メトロ",
    lines: ["丸ノ内線", "南北線"],
    lat: 35.70746,
    lng: 139.75192,
    aliases: ["後楽園"],
  },
  {
    id: "station-kasuga",
    name: "春日駅",
    operator: "都営地下鉄",
    lines: ["三田線", "大江戸線"],
    lat: 35.70942,
    lng: 139.75321,
    aliases: ["春日"],
  },
  {
    id: "station-iidabashi",
    name: "飯田橋駅",
    operator: "東京メトロ・都営地下鉄",
    lines: ["東西線", "有楽町線", "南北線", "大江戸線"],
    lat: 35.70173,
    lng: 139.74593,
    aliases: ["飯田橋"],
  },
  {
    id: "station-ichigaya",
    name: "市ケ谷駅",
    operator: "東京メトロ・都営地下鉄",
    lines: ["有楽町線", "南北線", "新宿線"],
    lat: 35.69101,
    lng: 139.73561,
    aliases: ["市ケ谷", "市ヶ谷"],
  },
  {
    id: "station-yotsuya",
    name: "四ツ谷駅",
    operator: "東京メトロ",
    lines: ["丸ノ内線", "南北線"],
    lat: 35.68604,
    lng: 139.72947,
    aliases: ["四ツ谷", "四谷"],
  },
  {
    id: "station-higashi-shinjuku",
    name: "東新宿駅",
    operator: "東京メトロ・都営地下鉄",
    lines: ["副都心線", "大江戸線"],
    lat: 35.69792,
    lng: 139.70755,
    aliases: ["東新宿"],
  },
  {
    id: "station-nakano-sakaue",
    name: "中野坂上駅",
    operator: "東京メトロ・都営地下鉄",
    lines: ["丸ノ内線", "大江戸線"],
    lat: 35.69749,
    lng: 139.68265,
    aliases: ["中野坂上"],
  },
  {
    id: "station-nakano",
    name: "中野駅",
    operator: "東京メトロ",
    lines: ["東西線"],
    lat: 35.70563,
    lng: 139.66565,
    aliases: ["中野"],
  },
  {
    id: "station-ogikubo",
    name: "荻窪駅",
    operator: "東京メトロ",
    lines: ["丸ノ内線"],
    lat: 35.70408,
    lng: 139.61964,
    aliases: ["荻窪"],
  },
  {
    id: "station-toyosu",
    name: "豊洲駅",
    operator: "東京メトロ・ゆりかもめ",
    lines: ["有楽町線", "ゆりかもめ"],
    lat: 35.65486,
    lng: 139.79621,
    aliases: ["豊洲"],
  },
  {
    id: "station-tsukishima",
    name: "月島駅",
    operator: "東京メトロ・都営地下鉄",
    lines: ["有楽町線", "大江戸線"],
    lat: 35.66489,
    lng: 139.78486,
    aliases: ["月島"],
  },
  {
    id: "station-kachidoki",
    name: "勝どき駅",
    operator: "都営地下鉄",
    lines: ["大江戸線"],
    lat: 35.65852,
    lng: 139.77643,
    aliases: ["勝どき"],
  },
  {
    id: "station-monzen-nakacho",
    name: "門前仲町駅",
    operator: "東京メトロ・都営地下鉄",
    lines: ["東西線", "大江戸線"],
    lat: 35.67199,
    lng: 139.79568,
    aliases: ["門前仲町"],
  },
  {
    id: "station-kiyosumi-shirakawa",
    name: "清澄白河駅",
    operator: "東京メトロ・都営地下鉄",
    lines: ["半蔵門線", "大江戸線"],
    lat: 35.6821,
    lng: 139.79887,
    aliases: ["清澄白河"],
  },
  {
    id: "station-kinshicho",
    name: "錦糸町駅",
    operator: "東京メトロ",
    lines: ["半蔵門線"],
    lat: 35.69687,
    lng: 139.81384,
    aliases: ["錦糸町"],
  },
  {
    id: "station-daikanyama",
    name: "代官山駅",
    operator: "東急電鉄",
    lines: ["東横線"],
    lat: 35.6481,
    lng: 139.70317,
    aliases: ["代官山"],
  },
  {
    id: "station-naka-meguro",
    name: "中目黒駅",
    operator: "東京メトロ・東急電鉄",
    lines: ["日比谷線", "東横線"],
    lat: 35.64427,
    lng: 139.69916,
    aliases: ["中目黒"],
  },
  {
    id: "station-jiyugaoka",
    name: "自由が丘駅",
    operator: "東急電鉄",
    lines: ["東横線", "大井町線"],
    lat: 35.60745,
    lng: 139.66873,
    aliases: ["自由が丘"],
  },
  {
    id: "station-futako-tamagawa",
    name: "二子玉川駅",
    operator: "東急電鉄",
    lines: ["田園都市線", "大井町線"],
    lat: 35.61148,
    lng: 139.62644,
    aliases: ["二子玉川"],
  },
  {
    id: "station-sangen-jaya",
    name: "三軒茶屋駅",
    operator: "東急電鉄",
    lines: ["田園都市線", "世田谷線"],
    lat: 35.64374,
    lng: 139.66902,
    aliases: ["三軒茶屋"],
  },
  {
    id: "station-oimachi",
    name: "大井町駅",
    operator: "東急電鉄・東京臨海高速鉄道",
    lines: ["大井町線", "りんかい線"],
    lat: 35.60623,
    lng: 139.73486,
    aliases: ["大井町"],
  },
  {
    id: "station-shinagawa",
    name: "品川駅",
    operator: "京急電鉄",
    lines: ["本線"],
    lat: 35.628471,
    lng: 139.73876,
    aliases: ["品川"],
  },
  {
    id: "station-kita-shinagawa",
    name: "北品川駅",
    operator: "京急電鉄",
    lines: ["本線"],
    lat: 35.62296,
    lng: 139.73924,
    aliases: ["北品川"],
  },
  {
    id: "station-heiwajima",
    name: "平和島駅",
    operator: "京急電鉄",
    lines: ["本線"],
    lat: 35.57874,
    lng: 139.73478,
    aliases: ["平和島"],
  },
  {
    id: "station-keikyu-kamata",
    name: "京急蒲田駅",
    operator: "京急電鉄",
    lines: ["本線", "空港線"],
    lat: 35.56074,
    lng: 139.7238,
    aliases: ["京急蒲田"],
  },
  {
    id: "station-shimo-kitazawa",
    name: "下北沢駅",
    operator: "小田急電鉄・京王電鉄",
    lines: ["小田原線", "井の頭線"],
    lat: 35.66135,
    lng: 139.66601,
    aliases: ["下北沢"],
  },
  {
    id: "station-yoyogi-uehara",
    name: "代々木上原駅",
    operator: "東京メトロ・小田急電鉄",
    lines: ["千代田線", "小田原線"],
    lat: 35.66902,
    lng: 139.67968,
    aliases: ["代々木上原"],
  },
  {
    id: "station-sasazuka",
    name: "笹塚駅",
    operator: "京王電鉄",
    lines: ["京王線", "京王新線"],
    lat: 35.6737,
    lng: 139.66744,
    aliases: ["笹塚"],
  },
  {
    id: "station-meidaimae",
    name: "明大前駅",
    operator: "京王電鉄",
    lines: ["京王線", "井の頭線"],
    lat: 35.66889,
    lng: 139.65014,
    aliases: ["明大前"],
  },
  {
    id: "station-takadanobaba",
    name: "高田馬場駅",
    operator: "東京メトロ・西武鉄道",
    lines: ["東西線", "新宿線"],
    lat: 35.71216,
    lng: 139.70378,
    aliases: ["高田馬場"],
  },
  {
    id: "station-nerima",
    name: "練馬駅",
    operator: "西武鉄道・都営地下鉄",
    lines: ["池袋線", "豊島線", "西武有楽町線", "大江戸線"],
    lat: 35.73749,
    lng: 139.65328,
    aliases: ["練馬"],
  },
  {
    id: "station-tobunerima",
    name: "東武練馬駅",
    operator: "東武鉄道",
    lines: ["東上線"],
    lat: 35.76894,
    lng: 139.66258,
    aliases: ["東武練馬"],
  },
  {
    id: "station-narimasu",
    name: "成増駅",
    operator: "東武鉄道",
    lines: ["東上線"],
    lat: 35.77766,
    lng: 139.63263,
    aliases: ["成増"],
  },
  {
    id: "station-keisei-ueno",
    name: "京成上野駅",
    operator: "京成電鉄",
    lines: ["京成本線"],
    lat: 35.71149,
    lng: 139.77361,
    aliases: ["京成上野"],
  },
  {
    id: "station-nippori",
    name: "日暮里駅",
    operator: "京成電鉄・日暮里・舎人ライナー",
    lines: ["京成本線", "日暮里・舎人ライナー"],
    lat: 35.72777,
    lng: 139.77099,
    aliases: ["日暮里"],
  },
  {
    id: "station-aoto",
    name: "青砥駅",
    operator: "京成電鉄",
    lines: ["京成本線", "押上線"],
    lat: 35.74582,
    lng: 139.85609,
    aliases: ["青砥"],
  },
  {
    id: "station-akihabara",
    name: "秋葉原駅",
    operator: "東京メトロ・つくばエクスプレス",
    lines: ["日比谷線", "つくばエクスプレス"],
    lat: 35.698353,
    lng: 139.773114,
    aliases: ["秋葉原"],
  },
  {
    id: "station-takeshiba",
    name: "竹芝駅",
    operator: "ゆりかもめ",
    lines: ["ゆりかもめ"],
    lat: 35.65477,
    lng: 139.76224,
    aliases: ["竹芝"],
  },
  {
    id: "station-daiba",
    name: "台場駅",
    operator: "ゆりかもめ",
    lines: ["ゆりかもめ"],
    lat: 35.62594,
    lng: 139.77131,
    aliases: ["台場"],
  },
  {
    id: "station-tamachi",
    name: "田町駅",
    operator: "JR東日本",
    lines: ["山手線", "京浜東北線"],
    lat: 35.645736,
    lng: 139.747575,
    aliases: ["田町"],
  },
  {
    id: "station-hamamatsucho",
    name: "浜松町駅",
    operator: "JR東日本・東京モノレール",
    lines: ["山手線", "京浜東北線", "東京モノレール羽田空港線"],
    lat: 35.655391,
    lng: 139.757135,
    aliases: ["浜松町"],
  },
  {
    id: "station-osaki",
    name: "大崎駅",
    operator: "JR東日本・東京臨海高速鉄道",
    lines: ["山手線", "埼京線", "湘南新宿ライン", "りんかい線"],
    lat: 35.6197,
    lng: 139.7286,
    aliases: ["大崎"],
  },
  {
    id: "station-gotanda",
    name: "五反田駅",
    operator: "JR東日本・東急電鉄・都営地下鉄",
    lines: ["山手線", "池上線", "浅草線"],
    lat: 35.626446,
    lng: 139.723444,
    aliases: ["五反田"],
  },
  {
    id: "station-meguro",
    name: "目黒駅",
    operator: "JR東日本・東急電鉄・東京メトロ・都営地下鉄",
    lines: ["山手線", "目黒線", "南北線", "三田線"],
    lat: 35.633998,
    lng: 139.715828,
    aliases: ["目黒"],
  },
  {
    id: "station-kamata",
    name: "蒲田駅",
    operator: "JR東日本・東急電鉄",
    lines: ["京浜東北線", "池上線", "東急多摩川線"],
    lat: 35.562479,
    lng: 139.71605,
    aliases: ["蒲田"],
  },
  {
    id: "station-mejiro",
    name: "目白駅",
    operator: "JR東日本",
    lines: ["山手線"],
    lat: 35.721204,
    lng: 139.706587,
    aliases: ["目白"],
  },
  {
    id: "station-otsuka",
    name: "大塚駅",
    operator: "JR東日本・東京都交通局",
    lines: ["山手線", "都電荒川線"],
    lat: 35.73139,
    lng: 139.72818,
    aliases: ["大塚", "大塚駅前"],
  },
  {
    id: "station-sugamo",
    name: "巣鴨駅",
    operator: "JR東日本・都営地下鉄",
    lines: ["山手線", "三田線"],
    lat: 35.733492,
    lng: 139.739345,
    aliases: ["巣鴨"],
  },
];
